### ISSUE TITLE
安装后无法import

### ISSUE THREAD

**Issue by itboyljm** [eedalong/pynuma#13]
如题，不管在Mac还是在Linux上面pip install成功后打开python shell都无法import numa，报错：
ModuleNotFoundError: No module named 'numa'

**Comment by eedalong** [comment]
哦哦哦，好的好的。我们看下这个问题，今天给您这边回复～

**Comment by eedalong** [comment]
@itboyljm  pip install --upgrade py-libnuma 请升级安装最新的package

**Comment by eedalong** [comment]
以及，numa特性是需要numa硬件架构支持的。这个目前只在linux下能够使用。mac底下的话应该是没法使用的～
